name: Workflow for API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  RESTBOOKER_USERNAME: ${{secrets.RESTBOOKER_USERNAME}}
  RESTBOOKER_PASSWORD: ${{secrets.RESTBOOKER_PASSWORD}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: API Tests
        run: mvn clean test -Pregression -q
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: allure-results
          path: allure-results
